#!/bin/bash
# Skript väljastab ristküliku kasutaja määratud suurusega

echo -n "Sisesta ridade arv: "
read read_arv
echo -n "Sisesta tärnide arv reas: "
read tarnid

for ((i=1; i<=read_arv; i++)); do
    echo -n "$i. "
    for ((j=1; j<=tarnid; j++)); do
        echo -n "* "
    done
    echo
done
