#!/bin/bash
# Skript väljastab raami kujundi

echo -n "Sisesta ridade arv: "
read read_arv
echo -n "Sisesta tärnide arv reas: "
read tarnid

for ((i=1; i<=read_arv; i++)); do
    echo -n "$i. "
    for ((j=1; j<=tarnid; j++)); do
        if [ $i -eq 1 -o $i -eq $read_arv -o $j -eq 1 -o $j -eq $tarnid ]; then
            echo -n "* "
        else
            echo -n "  "
        fi
    done
    echo
done
