#!/bin/bash
# Skript väljastab kolmnurga kujundi

echo -n "Sisesta ridade arv: "
read read_arv

for ((i=1; i<=read_arv; i++)); do
    echo -n "$i. "
    for ((j=1; j<=i; j++)); do
        echo -n "* "
    done
    echo
done
