#!/bin/bash
# Skript väljastab diagonaalse kujundi 'o' ja '*'

echo -n "Sisesta ridade arv: "
read read_arv

for ((i=1; i<=read_arv; i++)); do
    echo -n "$i. "
    for ((j=1; j<=read_arv; j++)); do
        if [ $j -lt $((read_arv - i + 1)) ]; then
            echo -n "o "
        else
            echo -n "* "
        fi
    done
    echo
done
