#!/bin/bash
# Skript kontrollib, kas arv on algarv

echo -n "Sisesta suvaline arv: "
read arv

if ! [[ "$arv" =~ ^[0-9]+$ ]]; then
    echo "Palun sisesta positiivne täisarv."
    exit 1
fi

if [ $arv -lt 2 ]; then
    echo "$arv - ei ole algarv"
    exit 0
fi

jagaja=2
while [ $((arv % jagaja)) -ne 0 -a $jagaja -lt $arv ]; do
    jagaja=$((jagaja + 1))
done

if [ $jagaja -eq $arv ]; then
    echo "$arv - on algarv"
else
    echo "$arv - ei ole algarv"
fi
