#!/bin/bash
# Skript väljastab 20 esimese arvu kohta, kas nad on algarvud

for ((n=1; n<=20; n++)); do
    if [ $n -lt 2 ]; then
        echo "$n - ei ole algarv"
        continue
    fi

    jagaja=2
    while [ $((n % jagaja)) -ne 0 -a $jagaja -lt $n ]; do
        jagaja=$((jagaja + 1))
    done

    if [ $jagaja -eq $n ]; then
        echo "$n - on algarv"
    else
        echo "$n - ei ole algarv"
    fi
done
