#!/bin/bash
# Skript küsib kasutajalt OS valiku ja väljastab tulemuse

osch=0
echo "1. Unix (Sun Os)"
echo "2. Linux (Red Hat)"

echo -n "Select your OS choice [1 or 2]? "
read osch

if [ $osch -eq 1 ] ; then
    echo "You Pick up Unix (Sun Os)"
else
    if [ $osch -eq 2 ] ; then
        echo "You Pick up Linux (Red Hat)"
    else
        echo "What, you don't like Unix/Linux OS."
    fi
fi
